//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodePatient
    {
        public int Id { get; set; }
        public string Bracode { get; set; }
        public int IdPatient { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
