//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompanyAccounts
    {
        public int IdAccountant { get; set; }
        public int IdOrder { get; set; }
        public int IdInsuranceCompany { get; set; }
        public decimal InvoiceIssued { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
