//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.InsuranceCompanyAccounts = new HashSet<InsuranceCompanyAccounts>();
            this.OrderLaboratoryServices = new HashSet<OrderLaboratoryServices>();
            this.ServiceRendered = new HashSet<ServiceRendered>();
        }
    
        public int IdOrder { get; set; }
        public int IdPatient { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public bool OrderStatus { get; set; }
        public int ExecutionTime { get; set; }
    
        public virtual AnalyzerOperationOrder AnalyzerOperationOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCompanyAccounts> InsuranceCompanyAccounts { get; set; }
        public virtual Patients Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLaboratoryServices> OrderLaboratoryServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRendered> ServiceRendered { get; set; }
    }
}
